### ISSUE TITLE
Include a Waifus generator

### ISSUE THREAD

**Issue by jeluchu** [aruppi/aruppi-api#17]
**Is your feature request related to a problem? Please describe.**
The idea is to create a waifus generator through a database with the names of all the waifus of the series along with a photograph, this feature would be included in the API and within the app, in which you could save the ones you like as favorites and share them.

**Comment by guillermoriv** [comment]
Can you be more specific about this waifu generator?, if you give me something more specific maybe i can implement it in the **API**

**Comment by jeluchu** [comment]
> It is easy, the thing would be to introduce a call in which you return the image and the name (and if possible the name of the series) of a Waifu randomly, making a query to the database, here is a link to a database (although the last update is 2 years ago so many new Waifus will be missing) >> https://www.kaggle.com/corollari/waifus

On the other hand you can also check out some other sites that I have found that do similar work:

http://randomwaifu.altervista.org
https://mywaifulist.moe/dash
https://waifu.pics
https://waifu.pics/api/sfw/slap
https://www.kaggle.com/mcparadip/anime-faces-waifu2x

**Comment by jeluchu** [comment]
An initial version is included within the application, later an endpoint will be included in the API for direct use.
