### ISSUE TITLE
Error loading the "AllThemes" directory

### ISSUE THREAD

**Issue by jeluchu** [aruppi/aruppi-api#5]
**Describe the bug**
An error is received when making the request through Retrofit in Android because inside the directory of all the themes a storing is returned that cannot be treated: **animedb.pl?show=anime&amp;aid=8624**

**Expected behavior**
That the JSON received is shown without strings of that type, we understand that some special character types are not accepted correctly, so if a storing with those characteristics is found it should be removed before returning it as a result of the call

**Screenshots**
https://ibb.co/1XD8jtV

**Comment by capitanwesler** [comment]
This error is solved in the **version 4** of the **API**, using the database as reference, solved in this commit in the version 4 SHA-7b8dca11fcf11c5ecb521819e5359496ad358237

**Comment by capitanwesler** [comment]
This error is solved in the version 4 of the API, using the database as reference, solved in this commit in the version 4 7b8dca11fcf11c5ecb521819e5359496ad358237

**Comment by guillermoriv** [comment]
This error is solved in the version 4 of the API, using the database as reference, solved in this commit in the version 4 7b8dca11fcf11c5ecb521819e5359496ad358237
