### ISSUE TITLE
No module found 

### ISSUE THREAD

**Issue by depezo** [aruppi/aruppi-api#55]
Hello !
I have a problem with the script, I get the message "No module found" when I type the command: "npm start" 

Screenshot : [https://tutodugeek.com/no_module_found.jpg](url)

**Comment by jeluchu** [comment]
In the photo you put inside the incident, you can't see anything at all.

Anyway, since version v4.0.0.0 of the API we recommend that you build with `yarn start` and `yarn build`.

**Comment by Darkangeel-hd** [comment]
@depezo 

For starters, this project uses `yarn` not `npm`, and while it should work with it, we wont be providing support for it as we are short staffed right now.

before running the api you must install all it's dependencies (`yarn install`)
then compiling ts to js is needed (use `yarn build`)
you should configure the correct env vars
there's a `.env.example` file with current config, you can copy that to `.env` and adjust it to your environment.

Also, the domain of the link you posted seems to be up for sale, u may want to look after that.

Also, using `npm` on my end seems to start the app fine:
![terminal screenshot](https://user-images.githubusercontent.com/10299587/185517784-a08e8d2b-5483-4648-b247-9dc25a6c5460.png)

So unless you provide us with more info we will close this issue.

**Comment by depezo** [comment]
Thanks !
