### ISSUE TITLE
Endpoint v4

### ISSUE THREAD

**Issue by kass507** [aruppi/aruppi-api#56]
Where do I find the v4 endpoints?
When trying to use /v3/news, it keeps loading.

I am not using the project locally, but on endpoint from the address: https://aruppi-api.herokuapp.com/api/v3/

And https://aruppi-api.herokuapp.com/api/v4/ does not exist

**Comment by Darkangeel-hd** [comment]
Hello @kass507, thanks for your interest in our project.

As of now we don't have and officially publicly available API endpoint.
Also, the Heroku one is long gone by now.

For the best availability, you should set the api locally or in a server of your own

What is your intended use of the api?

**Comment by jeluchu** [comment]
As such the endpoint pointing to Heroku stayed with the legacy version of v3,
which would be the latest released version, v3.4.7

https://aruppi-api.herokuapp.com/api/v3/

**Comment by kass507** [comment]
> .
Estaba por integrarlo a mi bot de discord.
La intencion era mostrar a traves de diversos comandos, informacion de anime. Al igual que mostrar eventos cada vez que se agregaba un anime nuevo o noticia o parecido.
---------
I was about to integrate it into my discord bot.
The intention was to show through various commands, anime information. As well as showing events every time a new anime or news or similar was added.

**Comment by kass507** [comment]
> As such the endpoint pointing to Heroku stayed with the legacy version of v3, which would be the latest released version, v3.4.7
> 
> https://aruppi-api.herokuapp.com/api/v3/

Algunos no son funcionales, por ejemplo: https://aruppi-api.herokuapp.com/api/v3/news

**Comment by Darkangeel-hd** [comment]
@kass507 
La api no está en un punto de desarrollo estable, varias llamadas han cambiado o van a cambiar en algun momento.
Si va a ser un bot al cual le prevees bastante uso, te recomiendo montar tu propia instancia de la api.
Aunque por desgracia aun no tenemos documentación del proceso de setup.
El único enpoint de la api que conocemos es el que usa al aplicación de Aruppi, y como tal es un endpoint privado y que tiene un rate limit de peticiones.
por lo que no creo que cumpla con las expectativas que tienes.

No obstante, te recomiendo echarle un ojo a la api de Jikan (https://jikan.moe), que es una de las fuentes que integramos en Aruppi.
Ellos si disponen de una api publica, con limites claros y buena documentacion, por lo tanto lo mismo te resulta mas interesante.

TLDR:
No existe actualmente un endpoint de la api v4 de aruppi para uso publico sin limitaciones.
Revisa si Jikan cumple con tus requisitos.

No se si sería posible discutir con @jeluchu un acuerdo de uso de la api, yo solo puedo hablar de la parte técnica

**Comment by kass507** [comment]
@Darkangeel-hd gracias por la info. Habia intentando  montar la api, pero la quia en ingles se me dificultaba entender, ademas que trabajodesde Windows. Adicional  intentaba evitar montarla debido a limitaciones del hardware de mi equipo, ya que de por si esta usado para correr los script y bots que tengo y está algo escaso de rendimiento.

Mirando jikan, veo que mas es una base de datos en ingles. Aunque sé que la usan, pero aruppi tiene mas endpoint para sitios y datos en español latino

**Comment by jeluchu** [comment]
@kass507 entiendo que algunos endpoints no sean funcionales como puede ser 
https://aruppi-api.herokuapp.com/api/v3/news o incluso seguro que hay alguno más

La versión v3 de la API dejó de recibir nuevas actualizaciones desde hace uno o dos años ya, después de varios meses después desde que se lanzó la versión v4. He intentado levantar la API en Heroku, pero por alguna razón no funciona el vincular la cuenta de GitHub con Heroku, por lo que no he conseguido levantar la API v4.

Como dice @Darkangeel-hd actualmente la API se usa de forma privada para dar datos a la app de [Aruppi](http://aruppi.jeluchu.com) y no hay un endpoint público para su uso, además del ratelimit. Como te indica @Darkangeel-hd, usamos [Jikan](https://jikan.moe/) para obtener ciertos datos, pero no todos, ya que los datos que devuelve están en inglés, además de que el endpoint de noticias que me indicabas no es de Jikan, se desarrolló exclusivamente para obtener noticias de diversas páginas de anime para mostrarlas dentro de Aruppi, por lo que seguramente hay muchos endpoints que usas que son exclusivos de la API de Aruppi.

Para montar la API en local con Windows necesitarías tal vez instalar Redis ya que en la v4 se implementó un sistema de caché con Redis y MongoDb, y por otra parte, en principio la API te debería funcionar con menos de 1GB de RAM ya que se optimizó para que funcionase con pocos recursos.

Por otra parte se podría revisar un acuerdo de uso de la API con el endpoint privado
